version: 2
jobs:
  build:
    docker:
      - image: python:latest
    working_directory: ~/djextra
    steps:
      - checkout
      - restore_cache:
          keys:
            - djextra-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run :
          name: "Run Venv"
          command: "python -m venv venv"
      - run:
          name: "Install Dependencies"
          command: |
            source ./venv/bin/activate &&
            pip install -r requirements.txt
      - save_cache:
          key: djextra-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "./venv"
      - run:
          name: "Test"
          command: source ./venv/bin/activate && tox
      - run:
          name: "Build"
          command: "python setup.py sdist bdist_wheel"
      - persist_to_workspace:
          root: ./
          paths:
            - venv
            - dist
  deploy:
    docker:
      - image: python:latest
    working_directory: ~/djextra
    steps:
      - attach_workspace:
          at: ./
      - run:
          name: "Deploy"
          command: "source ./venv/bin/activate && twine upload dist/*"

release_filter: &release_filter
  tags:
    only: /^(?:[0-9]+\.){2}[0-9].*/
  branches:
    ignore: /.*/

dev_filter: &dev_filter
  tags:
    ignore: /^(?:[0-9]+\.){2}[0-9].*/

workflows:
  version: 2
  default:
    jobs:
      - build:
          filters:
            << : *dev_filter
      - deploy:
          requires:
            - build
          filters:
            << : *dev_filter
  version_tag:
    jobs:
      - build:
          filters:
            << : *release_filter
      - deploy:
          requires:
            - build
          filters:
            << : *release_filter
